In [1]:

# 1. Data manipulation
import pandas as pd
import numpy as np

# 2. Data visualization
import matplotlib.pyplot as plt
import seaborn as sns

# 3. Data preprocessing and feature engineering
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# 4. Machine learning models
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.dummy import DummyClassifier

# 5. Model evaluation
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    confusion_matrix,
    classification_report,
    roc_curve,
    precision_recall_curve
)

# 6. Neural network
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.callbacks import EarlyStopping

# 7. Explainable AI
import shap
from sklearn.inspection import permutation_importance
from lime.lime_tabular import LimeTabularExplainer

# 8. Utilities
import warnings
warnings.filterwarnings("ignore")

# Reproducibility
np.random.seed(42)
tf.random.set_seed(42)

print("All imports completed successfully!")

All imports completed successfully!

In [2]:

import os
import glob

# Set the dataset folder path from Kaggle's Input section
data_folder = "/kaggle/input/datasets/rohanrao/formula-1-world-championship-1950-2020"

# Find all CSV files inside the dataset folder
csv_files = glob.glob(
    os.path.join(data_folder, "**", "*.csv"),
    recursive=True
)

# Load all CSV files into a dictionary
data = {
    os.path.splitext(os.path.basename(file))[0]: pd.read_csv(
        file, na_values=[r"\N"]
    )
    for file in csv_files
}

# Display the loaded tables
print("Number of CSV files loaded:", len(data))

for name, df in data.items():
    print(f"{name}: {df.shape}")

Number of CSV files loaded: 14
races: (1125, 18)
constructor_results: (12625, 5)
drivers: (861, 9)
constructors: (212, 5)
lap_times: (589081, 6)
status: (139, 2)
driver_standings: (34863, 7)
seasons: (75, 2)
pit_stops: (11371, 7)
sprint_results: (360, 16)
constructor_standings: (13391, 7)
results: (26759, 18)
circuits: (77, 9)
qualifying: (10494, 9)

In [3]:
for name, df in data.items(): #checking first 5 rows of each table fel dataset 
    print(f"\n{'=' * 50}")
    print(f"Table: {name}")
    print(f"Shape: {df.shape}")
    display(df.head())

==================================================
Table: races
Shape: (1125, 18)

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

==================================================
Table: constructor_results
Shape: (12625, 5)

   constructorResultsId  raceId  constructorId  points status
0                     1      18              1    14.0    NaN
1                     2      18              2     8.0    NaN
2                     3      18              3     9.0    NaN
3                     4      18              4     5.0    NaN
4                     5      18              5     2.0    NaN

==================================================
Table: drivers
Shape: (861, 9)

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44.0,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,NaN,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6.0,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14.0,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,NaN,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

==================================================
Table: constructors
Shape: (212, 5)

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso

==================================================
Table: lap_times
Shape: (589081, 6)

   raceId  driverId  lap  position      time  milliseconds
0     841        20    1         1  1:38.109         98109
1     841        20    2         1  1:33.006         93006
2     841        20    3         1  1:32.713         92713
3     841        20    4         1  1:32.803         92803
4     841        20    5         1  1:32.342         92342

==================================================
Table: status
Shape: (139, 2)

   statusId        status
0         1      Finished
1         2  Disqualified
2         3      Accident
3         4     Collision
4         5        Engine

==================================================
Table: driver_standings
Shape: (34863, 7)

   driverStandingsId  raceId  driverId  points  position positionText  wins
0                  1      18         1    10.0         1            1     1
1                  2      18         2     8.0         2            2     0
2                  3      18         3     6.0         3            3     0
3                  4      18         4     5.0         4            4     0
4                  5      18         5     4.0         5            5     0

==================================================
Table: seasons
Shape: (75, 2)

   year                                                url
0  2009  http://en.wikipedia.org/wiki/2009_Formula_One_...
1  2008  http://en.wikipedia.org/wiki/2008_Formula_One_...
2  2007  http://en.wikipedia.org/wiki/2007_Formula_One_...
3  2006  http://en.wikipedia.org/wiki/2006_Formula_One_...
4  2005  http://en.wikipedia.org/wiki/2005_Formula_One_...

==================================================
Table: pit_stops
Shape: (11371, 7)

   raceId  driverId  stop  lap      time duration  milliseconds
0     841       153     1    1  17:05:23   26.898         26898
1     841        30     1    1  17:05:52   25.021         25021
2     841        17     1   11  17:20:48   23.426         23426
3     841         4     1   12  17:22:34   23.251         23251
4     841        13     1   13  17:24:10   23.842         23842

==================================================
Table: sprint_results
Shape: (360, 16)

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,fastestLapTime,statusId
0,1,1061,830,9,33,2,1.0,1,1,3,17,25:38.426,1538426.0,14.0,1:30.013,1
1,2,1061,1,131,44,1,2.0,2,2,2,17,+1.430,1539856.0,17.0,1:29.937,1
2,3,1061,822,131,77,3,3.0,3,3,1,17,+7.502,1545928.0,17.0,1:29.958,1
3,4,1061,844,6,16,4,4.0,4,4,0,17,+11.278,1549704.0,16.0,1:30.163,1
4,5,1061,846,1,4,6,5.0,5,5,0,17,+24.111,1562537.0,16.0,1:30.566,1

==================================================
Table: constructor_standings
Shape: (13391, 7)

,constructorStandingsId,raceId,constructorId,points,position,positionText,wins
0,1,18,1,14.0,1,1,1
1,2,18,2,8.0,3,3,0
2,3,18,3,9.0,2,2,0
3,4,18,4,5.0,4,4,0
4,5,18,5,2.0,5,5,0

==================================================
Table: results
Shape: (26759, 18)

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22.0,1,1.0,1,1,10.0,58,1:34:50.616,5690616.0,39.0,2.0,1:27.452,218.300,1
1,2,18,2,2,3.0,5,2.0,2,2,8.0,58,+5.478,5696094.0,41.0,3.0,1:27.739,217.586,1
2,3,18,3,3,7.0,7,3.0,3,3,6.0,58,+8.163,5698779.0,41.0,5.0,1:28.090,216.719,1
3,4,18,4,4,5.0,11,4.0,4,4,5.0,58,+17.181,5707797.0,58.0,7.0,1:28.603,215.464,1
4,5,18,5,1,23.0,3,5.0,5,5,4.0,58,+18.014,5708630.0,43.0,1.0,1:27.418,218.385,1

==================================================
Table: circuits
Shape: (77, 9)

,circuitId,circuitRef,name,location,country,lat,lng,alt,url
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18,http://en.wikipedia.org/wiki/Sepang_Internatio...
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130,http://en.wikipedia.org/wiki/Istanbul_Park

==================================================
Table: qualifying
Shape: (10494, 9)

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
0,1,18,1,1,22,1,1:26.572,1:25.187,1:26.714
1,2,18,9,2,4,2,1:26.103,1:25.315,1:26.869
2,3,18,5,1,23,3,1:25.664,1:25.452,1:27.079
3,4,18,13,6,2,4,1:25.994,1:25.691,1:27.178
4,5,18,2,2,3,5,1:25.960,1:25.518,1:27.236

In [4]:
#checking the datatypes
for name, df in data.items():
    print(f"\n--- {name} ---")
    print(data[name].dtypes)

--- races ---
raceId          int64
year            int64
round           int64
circuitId       int64
name           object
date           object
time           object
url            object
fp1_date       object
fp1_time       object
fp2_date       object
fp2_time       object
fp3_date       object
fp3_time       object
quali_date     object
quali_time     object
sprint_date    object
sprint_time    object
dtype: object

--- constructor_results ---
constructorResultsId      int64
raceId                    int64
constructorId             int64
points                  float64
status                   object
dtype: object

--- drivers ---
driverId         int64
driverRef       object
number         float64
code            object
forename        object
surname         object
dob             object
nationality     object
url             object
dtype: object

--- constructors ---
constructorId      int64
constructorRef    object
name              object
nationality       object
url               object
dtype: object

--- lap_times ---
raceId           int64
driverId         int64
lap              int64
position         int64
time            object
milliseconds     int64
dtype: object

--- status ---
statusId     int64
status      object
dtype: object

--- driver_standings ---
driverStandingsId      int64
raceId                 int64
driverId               int64
points               float64
position               int64
positionText          object
wins                   int64
dtype: object

--- seasons ---
year     int64
url     object
dtype: object

--- pit_stops ---
raceId           int64
driverId         int64
stop             int64
lap              int64
time            object
duration        object
milliseconds     int64
dtype: object

--- sprint_results ---
resultId            int64
raceId              int64
driverId            int64
constructorId       int64
number              int64
grid                int64
position          float64
positionText       object
positionOrder       int64
points              int64
laps                int64
time               object
milliseconds      float64
fastestLap        float64
fastestLapTime     object
statusId            int64
dtype: object

--- constructor_standings ---
constructorStandingsId      int64
raceId                      int64
constructorId               int64
points                    float64
position                    int64
positionText               object
wins                        int64
dtype: object

--- results ---
resultId             int64
raceId               int64
driverId             int64
constructorId        int64
number             float64
grid                 int64
position           float64
positionText        object
positionOrder        int64
points             float64
laps                 int64
time                object
milliseconds       float64
fastestLap         float64
rank               float64
fastestLapTime      object
fastestLapSpeed    float64
statusId             int64
dtype: object

--- circuits ---
circuitId       int64
circuitRef     object
name           object
location       object
country        object
lat           float64
lng           float64
alt             int64
url            object
dtype: object

--- qualifying ---
qualifyId         int64
raceId            int64
driverId          int64
constructorId     int64
number            int64
position          int64
q1               object
q2               object
q3               object
dtype: object

In [5]:
#checking missing values
for name, df in data.items():
    missing = df.isnull().sum()
    missing = missing[missing > 0].sort_values(ascending=False)

    print(f"\n--- {name} ---")

    if missing.empty:
        print("No missing values found.")
    else:
        missing_table = pd.DataFrame({
            "Missing Count": missing,
            "Missing Percentage (%)": (
                missing / len(df) * 100
            ).round(2)
        })
        display(missing_table)

--- races ---

             Missing Count  Missing Percentage (%)
sprint_time           1110                   98.67
sprint_date           1107                   98.40
fp3_time              1072                   95.29
quali_time            1057                   93.96
fp2_time              1057                   93.96
fp1_time              1057                   93.96
fp3_date              1053                   93.60
fp2_date              1035                   92.00
fp1_date              1035                   92.00
quali_date            1035                   92.00
time                   731                   64.98

--- constructor_results ---

        Missing Count  Missing Percentage (%)
status          12608                   99.87

--- drivers ---

        Missing Count  Missing Percentage (%)
number            802                   93.15
code              757                   87.92

--- constructors ---
No missing values found.

--- lap_times ---
No missing values found.

--- status ---
No missing values found.

--- driver_standings ---
No missing values found.

--- seasons ---
No missing values found.

--- pit_stops ---
No missing values found.

--- sprint_results ---

                Missing Count  Missing Percentage (%)
time                       20                    5.56
milliseconds               20                    5.56
position                   15                    4.17
fastestLap                  9                    2.50
fastestLapTime              9                    2.50

--- constructor_standings ---
No missing values found.

--- results ---

                 Missing Count  Missing Percentage (%)
milliseconds             19079                   71.30
time                     19079                   71.30
fastestLapTime           18507                   69.16
fastestLap               18507                   69.16
fastestLapSpeed          18507                   69.16
rank                     18249                   68.20
position                 10953                   40.93
number                       6                    0.02

--- circuits ---
No missing values found.

--- qualifying ---

    Missing Count  Missing Percentage (%)
q3           6865                   65.42
q2           4647                   44.28
q1            156                    1.49

In [6]:
#checking duplicayes
for name, df in data.items():
    print(
        f"{name}: {df.duplicated().sum()}  duplicated rows"
    )

races: 0  duplicated rows
constructor_results: 0  duplicated rows
drivers: 0  duplicated rows
constructors: 0  duplicated rows
lap_times: 0  duplicated rows
status: 0  duplicated rows
driver_standings: 0  duplicated rows
seasons: 0  duplicated rows
pit_stops: 0  duplicated rows
sprint_results: 0  duplicated rows
constructor_standings: 0  duplicated rows
results: 0  duplicated rows
circuits: 0  duplicated rows
qualifying: 0  duplicated rows

In [7]:
# Check whether primary IDs are duplicated
primary_keys = {
    "circuits": ["circuitId"],
    "constructors": ["constructorId"],
    "drivers": ["driverId"],
    "races": ["raceId"],
    "results": ["resultId"],
    "qualifying": ["qualifyId"],
    "status": ["statusId"]
}

for table, keys in primary_keys.items():
    if table in data and all(k in data[table].columns for k in keys):
        df = data[table]
        duplicates = df.duplicated(subset=keys).sum()

        print(f"{table}: {duplicates} duplicate IDs")

circuits: 0 duplicate IDs
constructors: 0 duplicate IDs
drivers: 0 duplicate IDs
races: 0 duplicate IDs
results: 0 duplicate IDs
qualifying: 0 duplicate IDs
status: 0 duplicate IDs